name: Windows MSI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-msi:
    name: Windows Installer (.msi)
    runs-on: windows-latest
    env:
      RUSTFLAGS: -C target-feature=+crt-static
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-wix
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-wix
      - name: Build MSI
        run: cargo wix --nocapture
      - name: Rename MSI for Winget
        shell: pwsh
        run: Move-Item target/wix/*.msi target/wix/Fount-Windows-Installer.msi
      - name: Upload MSI
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: target/wix/Fount-Windows-Installer.msi
          token: ${{ secrets.GITHUB_TOKEN }}
